version: '3.8'
services:
  backend:
    env_file:
      - "./backend/.env"
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    container_name: backend
    ports:
      - '5000:5000'
    volumes:
      - ./backend:/app
      - ./app/node_modules
  client:
    build:
      context: ./client
      dockerfile: ./Dockerfile
    container_name: client
    ports:
      - '5173:5173'
    volumes:
      - ./client:/app
      - ./app/node_modules
    stdin_open: true
    tty: true